apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
  - pairs:
      app.kubernetes.io/part-of: wac-hospital
      app.kubernetes.io/name: ros-ambulance-wl
    includeSelectors: true
    includeTemplates: true

resources:
  - ../../../apps/ros-ambulance-ufe
  - ../../../apps/ros-ambulance-webapi


components:
  - ../../../components/version-release
