apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ros-ambulance-ufe-content
spec:
  microFrontend: ros-ambulance-ufe
  element: ros-ambulance-wl-app
  attributes:
    - name: api-base
      value: /ros-api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?ros-ambulance-wl(/.*)?$"
